import type { Character } from "../../src/lib/character-types"

export const testCharacter: Character = {
  id: "visual-test-char-1",
  name: "Aria Swiftwind",
  race: "Elf",
  class: "Ranger",
  subclass: "Hunter",
  background: "Outlander",
  alignment: "Chaotic Good",
  level: 5,
  experiencePoints: 6500,
  edition: "2024",
  size: "Medium",

  abilityScores: {
    strength: 12,
    dexterity: 18,
    constitution: 14,
    intelligence: 10,
    wisdom: 16,
    charisma: 10,
  },
  savingThrows: {
    strength: false,
    dexterity: true,
    constitution: false,
    intelligence: false,
    wisdom: true,
    charisma: false,
  },
  skills: {
    acrobatics: { proficient: false, expertise: false },
    animalHandling: { proficient: true, expertise: false },
    arcana: { proficient: false, expertise: false },
    athletics: { proficient: false, expertise: false },
    deception: { proficient: false, expertise: false },
    history: { proficient: false, expertise: false },
    insight: { proficient: false, expertise: false },
    intimidation: { proficient: false, expertise: false },
    investigation: { proficient: false, expertise: false },
    medicine: { proficient: false, expertise: false },
    nature: { proficient: true, expertise: false },
    perception: { proficient: true, expertise: true },
    performance: { proficient: false, expertise: false },
    persuasion: { proficient: false, expertise: false },
    religion: { proficient: false, expertise: false },
    sleightOfHand: { proficient: false, expertise: false },
    stealth: { proficient: true, expertise: false },
    survival: { proficient: true, expertise: false },
  },

  hitPoints: { current: 38, maximum: 44, temporary: 5 },
  armorClass: 16,
  initiative: 4,
  speed: 35,
  proficiencyBonus: 3,
  deathSaves: { successes: 0, failures: 0 },
  hitDice: "5d10",
  spentHitDice: 1,
  hitDiceSize: 10,

  spellcastingAbility: "wisdom",
  spellSaveDC: 14,
  spellAttackBonus: 6,
  spellSlots: {
    1: { total: 4, used: 1 },
    2: { total: 2, used: 0 },
    3: { total: 0, used: 0 },
    4: { total: 0, used: 0 },
    5: { total: 0, used: 0 },
    6: { total: 0, used: 0 },
    7: { total: 0, used: 0 },
    8: { total: 0, used: 0 },
    9: { total: 0, used: 0 },
  },
  spells: [
    {
      id: "sp1",
      name: "Hunter's Mark",
      level: 1,
      school: "Divination",
      castingTime: "1 Bonus Action",
      range: "90 ft",
      components: "V",
      duration: "1 hour",
      description: "You choose a creature you can see within range and mystically mark it as your quarry. You deal an extra 1d6 damage to it whenever you hit it with an attack, and you have advantage on Perception and Survival checks to find it.",
      prepared: true,
      known: true,
      concentration: true,
    },
    {
      id: "sp2",
      name: "Ensnaring Strike",
      level: 1,
      school: "Conjuration",
      castingTime: "1 Bonus Action",
      range: "Self",
      components: "V",
      duration: "1 minute",
      description: "The next time you hit a creature with a weapon attack before this spell ends, a writhing mass of thorny vines appears at the point of impact.",
      prepared: true,
      known: true,
      concentration: true,
    },
    {
      id: "sp3",
      name: "Pass without Trace",
      level: 2,
      school: "Abjuration",
      castingTime: "1 Action",
      range: "Self",
      components: "V, S, M (ashes from a burned leaf of mistletoe and a sprig of spruce)",
      duration: "1 hour",
      description: "A veil of shadows and silence radiates from you, masking you and your companions from detection.",
      prepared: true,
      known: true,
      concentration: true,
    },
  ],

  equipment: [
    {
      id: "eq1",
      name: "Longbow",
      quantity: 1,
      weight: 2,
      description: "Ranged weapon, two-handed",
      equipped: true,
      type: "weapon",
      weaponStats: { damage: "1d8", damageType: "Piercing", weaponRange: "150/600 ft", attackAbility: "dex", proficient: true },
    },
    {
      id: "eq2",
      name: "Leather Armor",
      quantity: 1,
      weight: 10,
      description: "Light armor — AC 11 + DEX",
      equipped: true,
      type: "armor",
      armorStats: { baseAC: 11, armorType: "light" },
    },
    {
      id: "eq3",
      name: "Arrows (20)",
      quantity: 2,
      weight: 1,
      description: "Standard ammunition for a shortbow or longbow",
      equipped: false,
      type: "other",
    },
    {
      id: "eq4",
      name: "Shortsword",
      quantity: 1,
      weight: 2,
      description: "Melee weapon, finesse, light",
      equipped: true,
      type: "weapon",
      weaponStats: { damage: "1d6", damageType: "Piercing", weaponRange: "5 ft", attackAbility: "finesse", proficient: true },
    },
    {
      id: "eq5",
      name: "Herbalism Kit",
      quantity: 1,
      weight: 3,
      description: "Used to identify plants and brew antitoxin",
      equipped: false,
      type: "tool",
    },
    {
      id: "mi1",
      name: "Ring of Protection",
      quantity: 1,
      weight: 0,
      description: "+1 bonus to AC and saving throws while attuned.",
      equipped: false,
      type: "other",
      magic: true,
      requiresAttunement: true,
      attuned: true,
      rarity: "rare",
    },
  ],
  coins: { cp: 15, sp: 50, ep: 0, gp: 150, pp: 2 },

  attacks: [
    {
      id: "atk1",
      name: "Longbow Strike",
      type: "attack",
      attackBonus: 7,
      damage: "1d8+4",
      damageType: "Piercing",
      range: "150/600 ft",
      description: "Ranged weapon attack with proficiency",
    },
  ],
  bonusActions: [
    {
      id: "ba1",
      name: "Hunter's Mark",
      type: "ability",
      description: "Expend a spell slot to place Hunter's Mark on a creature within 90 ft, dealing an extra 1d6 damage on each hit.",
      range: "90 ft",
    },
  ],
  reactions: [
    {
      id: "re1",
      name: "Uncanny Dodge",
      type: "class-feature",
      trigger: "An attacker you can see hits you with an attack",
      description: "Use your reaction to halve the attack's damage against you.",
    },
  ],
  otherActions: [
    {
      id: "oa1",
      name: "Speak with Animals",
      type: "ability",
      description: "Cast as a ritual to communicate with beasts for 10 minutes.",
      uses: 3,
      maxUses: 3,
      rechargeOn: "long-rest",
    },
  ],

  classFeatures: [
    {
      id: "cf1",
      name: "Favored Enemy",
      source: "class-feature",
      description: "You have advantage on Survival checks to track your favored enemies, and advantage on Intelligence checks to recall information about them.",
    },
    {
      id: "cf2",
      name: "Natural Explorer",
      source: "class-feature",
      description: "You are particularly familiar with one type of natural environment. When traveling for an hour or more, you gain several benefits including no reduction from difficult terrain and no chance of getting lost.",
    },
    {
      id: "cf3",
      name: "Extra Attack",
      source: "class-feature",
      actionKind: "action",
      description: "When you take the Attack action on your turn, you can attack twice instead of once.",
    },
    {
      id: "cf4",
      name: "Colossus Slayer",
      source: "class-feature",
      description: "Your tenacity can wear down the most resilient foes. Once per turn, when you hit a creature with a weapon attack, you deal an extra 1d8 damage if it's below its hit point maximum.",
    },
  ],
  speciesTraits: [
    {
      id: "st1",
      name: "Darkvision",
      source: "species-trait",
      description: "Accustomed to twilit forests and the night sky, you have superior vision in dark and dim conditions. You can see in dim light within 60 feet as bright light, and in darkness as dim light.",
    },
    {
      id: "st2",
      name: "Fey Ancestry",
      source: "species-trait",
      description: "You have advantage on saving throws against being charmed, and magic can't put you to sleep.",
    },
    {
      id: "st3",
      name: "Trance",
      source: "species-trait",
      description: "Elves don't need to sleep. Instead, they meditate deeply, remaining semiconscious, for 4 hours a day. After resting this way, you gain the same benefit a human does from 8 hours of sleep.",
    },
  ],
  feats: [
    {
      id: "ft1",
      name: "Sharpshooter",
      source: "feat",
      description: "You have mastered ranged weapons and can make shots that others find impossible. Attacking at long range doesn't impose disadvantage. Your ranged weapon attacks ignore half cover and three-quarters cover. Before making an attack with a ranged weapon, you can choose to take a -5 penalty to the attack roll. If the attack hits, you add +10 to the attack's damage.",
    },
  ],

  languages: ["Common", "Elvish", "Sylvan"],
  otherProficiencies: ["Longbow", "Shortsword", "Herbalism Kit"],

  personalityTraits: "I always have a plan for when things go wrong.",
  ideals: "The natural world is more important than all the constructs of civilization.",
  bonds: "My family was killed by orcs. I hunt them relentlessly.",
  flaws: "I am slow to trust members of other races.",
  backstory: "Raised in the forests of Cormanthor, Aria became a ranger after her village was destroyed by a raiding orc warband. She spent years tracking the perpetrators, learning the ways of the wild and honing her skills as a hunter.",
  notes: "Speak with Animals: 3 uses remaining\nHunter's Mark active on the bandit chief.",
  appearance: "Slender elven build, silver hair worn in a braid, green eyes that miss nothing.",
  age: "125",
  height: "5'8\"",
  weight: "130 lbs",
  eyes: "Green",
  skin: "Tan",
  hair: "Silver",

  conditions: [],
  heroicInspiration: false,
  alliesAndOrganizations: "Order of the Emerald Enclave — a network of rangers and druids who protect the natural world.",
  treasure: "A locket containing a miniature portrait of her parents, before the raid.",
}

export const secondCharacter: Character = {
  ...testCharacter,
  id: "visual-test-char-2",
  name: "Brom Ironforge",
  race: "Dwarf",
  class: "Fighter",
  level: 3,
  hitPoints: { current: 0, maximum: 30, temporary: 0 },
  deathSaves: { successes: 1, failures: 2 },
}

/** Public character used for /share/:id visual tests. Has isPublic:true and uses trackers. */
export const publicCharacter: Character = {
  ...testCharacter,
  id: "visual-public-char-1",
  name: "Zara Moonwhisper",
  race: "Tiefling",
  class: "Warlock",
  level: 7,
  isPublic: true,
  otherActions: [
    {
      id: "oa-vis-1",
      name: "Dark One's Blessing",
      type: "class-feature",
      description: "Regain HP equal to Cha modifier + Warlock level when you reduce a hostile creature to 0 HP.",
      uses: 1,
      maxUses: 3,
      rechargeOn: "short-rest",
    },
    {
      id: "oa-vis-2",
      name: "Fiendish Resilience",
      type: "class-feature",
      description: "Choose one damage type. You gain resistance to that damage type until you use this feature again.",
      uses: 0,
      maxUses: 8,
      rechargeOn: "long-rest",
    },
  ],
}

/** Inject characters + skip-auth into localStorage before page load */
export function seedLocalStorage(characters: Character[]) {
  localStorage.setItem("dnd-characters", JSON.stringify(characters))
  localStorage.setItem("dnd-skip-auth", "true")
}
