import type { Character } from "../../src/lib/character-types"

export const testCharacter: Character = {
  id: "visual-test-char-1",
  name: "Aria Swiftwind",
  race: "Elf",
  class: "Ranger",
  background: "Outlander",
  alignment: "Chaotic Good",
  level: 5,
  experiencePoints: 6500,
  abilityScores: {
    strength: 12,
    dexterity: 18,
    constitution: 14,
    intelligence: 10,
    wisdom: 16,
    charisma: 10,
  },
  savingThrows: {
    strength: false,
    dexterity: true,
    constitution: false,
    intelligence: false,
    wisdom: true,
    charisma: false,
  },
  skills: {
    acrobatics: { proficient: false, expertise: false },
    animalHandling: { proficient: true, expertise: false },
    arcana: { proficient: false, expertise: false },
    athletics: { proficient: false, expertise: false },
    deception: { proficient: false, expertise: false },
    history: { proficient: false, expertise: false },
    insight: { proficient: false, expertise: false },
    intimidation: { proficient: false, expertise: false },
    investigation: { proficient: false, expertise: false },
    medicine: { proficient: false, expertise: false },
    nature: { proficient: true, expertise: false },
    perception: { proficient: true, expertise: true },
    performance: { proficient: false, expertise: false },
    persuasion: { proficient: false, expertise: false },
    religion: { proficient: false, expertise: false },
    sleightOfHand: { proficient: false, expertise: false },
    stealth: { proficient: true, expertise: false },
    survival: { proficient: true, expertise: false },
  },
  hitPoints: { current: 38, maximum: 44, temporary: 5 },
  armorClass: 16,
  initiative: 4,
  speed: 35,
  proficiencyBonus: 3,
  deathSaves: { successes: 0, failures: 0 },
  spellcastingAbility: "wisdom",
  spellSlots: {
    1: { used: 1, maximum: 4 },
    2: { used: 0, maximum: 2 },
    3: { used: 0, maximum: 0 },
    4: { used: 0, maximum: 0 },
    5: { used: 0, maximum: 0 },
    6: { used: 0, maximum: 0 },
    7: { used: 0, maximum: 0 },
    8: { used: 0, maximum: 0 },
    9: { used: 0, maximum: 0 },
  },
  spells: [],
  equipment: [
    { id: "eq1", name: "Longbow", quantity: 1, weight: 2, description: "Ranged weapon", equipped: true, type: "weapon" },
    { id: "eq2", name: "Leather Armor", quantity: 1, weight: 10, description: "Light armor", equipped: true, type: "armor" },
    { id: "eq3", name: "Arrows (20)", quantity: 1, weight: 1, description: "Ammunition", equipped: false, type: "other" },
  ],
  attacks: [],
  bonusActions: [],
  reactions: [],
  personalityTraits: "I always have a plan for when things go wrong.",
  ideals: "The natural world is more important than all the constructs of civilization.",
  bonds: "My family was killed by orcs. I hunt them relentlessly.",
  flaws: "I am slow to trust members of other races.",
  backstory: "Raised in the forests of Cormanthor, Aria became a ranger after her village was destroyed.",
  notes: "Speak with Animals: 3 uses remaining",
  languages: ["Common", "Elvish", "Sylvan"],
  otherProficiencies: ["Longbow", "Shortsword", "Herbalism Kit"],
  heroicInspiration: false,
  createdAt: new Date("2024-01-01").toISOString(),
  updatedAt: new Date("2024-01-01").toISOString(),
}

export const secondCharacter: Character = {
  ...testCharacter,
  id: "visual-test-char-2",
  name: "Brom Ironforge",
  race: "Dwarf",
  class: "Fighter",
  level: 3,
  hitPoints: { current: 0, maximum: 30, temporary: 0 },
  deathSaves: { successes: 1, failures: 2 },
}

/** Inject characters + skip-auth into localStorage before page load */
export function seedLocalStorage(characters: Character[]) {
  localStorage.setItem("dnd-characters", JSON.stringify(characters))
  localStorage.setItem("dnd-skip-auth", "true")
}
